export interface BrrrdManifest {
  version: 1 | 2;
  buildId: string;
  appBundle?: string;
  routes: BrrrdRoute[];
  staticDir: string;
  prerendersDir: string;
  runtimeDir: string;
  env: Record<string, string>;
  redirects?: BrrrdRedirect[];
  rewrites?: BrrrdRewrite[];
  /** A-1: Bundle path + matcher patterns when middleware.ts is present. */
  middleware?: BrrrdMiddleware;
  /** A-7: List of pages with Partial Prerendering enabled. An empty array means PPR is not used. */
  pprPages?: string[];
}

export interface BrrrdMiddleware {
  /** Absolute path to the Next webpack edge runtime (relative to the manifest outDir). */
  runtime: string;
  /** Relative path to the middleware.js (webpack chunk) generated by Next. */
  entry: string;
  /** Next's _ENTRIES key suffix (usually "middleware"). */
  name: string;
  /** The middleware's "page" (usually "/middleware" or "/proxy"). */
  page: string;
  /** Next matcher specification (the regexp is compiled as-is into a Rust regex). */
  matchers: BrrrdMiddlewareMatcher[];
  /** middleware-manifest.wasm — copied raw next to runtime files. */
  wasm: BrrrdMiddlewareFile[];
  /** middleware-manifest.assets — copied raw next to runtime files. */
  assets: BrrrdMiddlewareFile[];
  /** middleware-manifest.env — build-time constants to be merged into process.env. */
  env: Record<string, string>;

  /** @deprecated Kept for compatibility (old manifest reader). Always an empty array. */
  bundle?: string;
}

export interface BrrrdMiddlewareMatcher {
  regexp: string;
  originalSource: string;
  has?: BrrrdMiddlewareCondition[];
  missing?: BrrrdMiddlewareCondition[];
}

export interface BrrrdMiddlewareCondition {
  type: "header" | "cookie" | "query" | "host";
  key: string;
  value?: string;
}

export interface BrrrdMiddlewareFile {
  name?: string;
  filePath: string;
}

export interface BrrrdRedirect {
  regex: string;
  destination: string;
  statusCode: number;
}

export interface BrrrdRewrite {
  regex: string;
  destination: string;
}

export interface BrrrdRoute {
  id: string;
  pattern: string;
  type: "page" | "route" | "static" | "prerender";
  runtime: "nodejs";
  bundle?: string;
  file?: string;
  params?: string[];
  immutable?: boolean;
}

export interface BuildContext {
  projectDir: string;
  distDir: string;
  outDir: string;
  buildId: string;
}
